web3j:
  client-address: http://192.168.31.49:8545
  admin-client: true
  chain-id: 123456
  
spring:
  data:
    mongodb:
      uri: mongodb://120.78.138.197:27017/betwin
  application:
    name: BetWin