package com.betwin.contract.service;

import java.math.BigInteger;
import java.util.concurrent.ExecutionException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.parity.Parity;

import com.betwin.contract.autogenerated.Counter;
import com.betwin.util.Web3jConstants;
import com.betwin.util.Web3jUtils;

@Service
public class CounterContractService extends AContractService {

	@Autowired
	private Parity web3j;

	@Value("${privatekey.account-from:}")
	private String privateKey;

	private Counter counter;

	private static Logger log = LoggerFactory.getLogger(CounterContractService.class);

	@Override
	public String deployContract() throws Exception {
		Credentials credentials = Credentials.create("0x" + privateKey);
		contract = Counter.deploy(web3j, credentials, Web3jConstants.GAS_PRICE, Web3jConstants.GAS_LIMIT_GREETER_TX)
				.sendAsync().get();

		// get tx receipt
		TransactionReceipt txReceipt = contract.getTransactionReceipt().get();

		// get tx hash and tx fees
		String deployHash = txReceipt.getTransactionHash();
		BigInteger deployFees = txReceipt.getCumulativeGasUsed().multiply(Web3jConstants.GAS_PRICE);

		counter = (Counter) contract;

		log.info("Deploy hash: " + deployHash);
		log.info("Deploy fees: " + Web3jUtils.weiToGwei(deployFees));

		return "";
	}

	public int getCounter() throws InterruptedException, ExecutionException {
		return counter.getCount().sendAsync().get().intValue();
	}

	public void increaseCounter() throws InterruptedException, ExecutionException {
		counter.incrementCounter().sendAsync().get();
	}

	public void decreaseCounter() throws InterruptedException, ExecutionException {
		counter.decrementCounter().sendAsync().get();
	}
}
